name: Python3 3.6.5
channels:
- menpo
- anaconda
- conda-forge
- defaults
dependencies:
- blas=1.0
- pyshp=2.0.1
- basemap=1.2.0
- cachetools=2.0.1
- cartopy=0.17.0
- cld2-cffi=0.1.4
- cmake=3.11.3
- curl=7.60.0
- expat=2.2.5
- geos=3.7.1
- ijson=2.3
- krb5=1.14.6
- libedit=3.1.20170329
- libiconv=1.15
- libssh2=1.8.0
- libtiff=4.0.9
- libuv=1.20.3
- libxml2=2.9.8
- libxslt=1.1.32
- lxml=4.3.2
- ncurses=5.9
- networkx=2.1
- olefile=0.46
- owslib=0.17.1
- pandas=0.20.3
- patsy=0.4.1
- proj4=5.2.0
- pyemd=0.4.4
- pyepsg=0.4.0
- pykdtree=1.3.1
- pyphen=0.9.4
- python-levenshtein=0.12.0
- readline=7.0
- rhash=1.3.4
- shapely=1.6.4
- unidecode=0.04.21
- asn1crypto=0.24.0
- bleach=2.1.3
- boost=1.65.1
- boto=2.49.0
- boto3=1.7.62
- botocore=1.10.62
- bzip2=1.0.6
- ca-certificates=2018.03.07
- certifi=2018.1.18
- cffi=1.11.4
- chardet=3.0.4
- cryptography=2.0.3
- cycler=0.10.0
- cymem=2.0.2
- cytoolz=0.9.0.1
- decorator=4.2.1
- dill=0.2.7.1
- docutils=0.14
- entrypoints=0.2.3
- freetype=2.9.1
- ftfy=4.4.3
- gensim=3.4.0
- html5lib=1.0.1
- icu=58.2
- idna=2.6
- intel-openmp=2019.3
- ipykernel=4.8.2
- ipython=6.2.1
- ipython_genutils=0.2.0
- jedi=0.11.1
- jinja2=2.10
- jmespath=0.9.3
- jpeg=9b
- jsonschema=2.6.0
- jupyter_client=5.2.2
- jupyter_core=4.4.0
- kiwisolver=1.0.1
- libboost=1.65.1
- libffi=3.2.1
- libpng=1.6.36
- libsodium=1.0.15
- markupsafe=1.0
- matplotlib=3.0.2
- mistune=0.8.3
- mkl=2018.0.3
- mkl_fft=1.0.6
- mkl_random=1.0.1
- msgpack-numpy=0.4.1
- msgpack-python=0.6.1
- murmurhash=1.0.2
- nbconvert=5.3.1
- nbformat=4.4.0
- numpy=1.15.4
- numpy-base=1.15.4
- openssl=1.0.2o
- pandoc=1.19.2.1
- pandocfilters=1.4.2
- parso=0.1.1
- pathlib=1.0.1
- pexpect=4.4.0
- pickleshare=0.7.4
- pillow=5.2.0
- pip=9.0.1
- plac=0.9.6
- preshed=2.0.1
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- py-boost=1.65.1
- py4j=0.10.7
- pycparser=2.18
- pygments=2.2.0
- pyopenssl=17.4.0
- pyparsing=2.2.00
- pyproj=1.9.5.1
- pyqt=5.6.0
- pysocks=1.6.7
- pyspark=2.3.1
- python=3.6.5
- python-dateutil=2.6.1
- pytz=2017.2
- pyzmq=16.0.3
- qt=5.6.2
- regex=2019.03.09
- requests=2.18.4
- s3transfer=0.1.13
- scikit-learn=0.20.1
- scipy=1.1.0
- seaborn=0.8.1
- setuptools=27.2.0
- simplegeneric=0.8.1
- sip=4.18
- six=1.10.0
- smart_open=1.6.0
- spacy=2.0.16
- sqlite=3.26.0
- statsmodels=0.8.0
- tabulate=0.8.2
- termcolor=1.1.0
- testpath=0.3.1
- thinc=6.12.1
- tk=8.6.7
- toolz=0.9.0
- tornado=4.5.3
- tqdm=4.19.4
- traitlets=4.3.2
- ujson=1.35
- unzip=6.0
- urllib3=1.22
- wcwidth=0.1.7
- webencodings=0.5.1
- wget=1.19.5
- wheel=0.29.0
- wrapt=1.10.11
- xz=5.2.4
- zeromq=4.2.2
- zlib=1.2.11
- eigen=3.2.7
