name: Python3 3.6.5
channels:
- menpo
- anaconda
- conda-forge
- defaults
dependencies:
- jupyter_client=5.2.2
- jupyter_core=4.4.0
- nltk=3.2.4
- numpy=1.15.4
- numpy-base=1.15.4
- pickleshare=0.7.4
- python=3.6.5
- scikit-learn=0.20.1
- scipy=1.1.0
